### ISSUE TITLE
vim-pyenv updates PYTHONPATH, but vim still uses system python

### ISSUE THREAD

**Issue by alexhbnr** [lambdalisue/vim-pyenv#8]
Hello,

I rather have a question about the functionality of vim-pyenv. I use the repository version of vim that comes along with Ubuntu 14.04 (compiled with +python, -python3 and linked against the system python). Additionally, I have another python2 version installed using pyenv.

Using vim-pyenv I now can append the PYTHONPATH in vim to look for libraries in my pyenv version of Python, which works totally fine. But the ":python" command is still using the system python version rather than the pyenv python version resulting in conflicts with jedi-vim.

Is there a way to use vim-pyenv to change the python version at is used in the ": python" command when vim was compiled with being linked to the system python?

Cheers!

**Comment by lambdalisue** [comment]
No, you can't. Vim was **compiled** with the system python so you have to **re-compile** Vim to refer the pyenv python. That's why I made this plugin to quickly refer the compatible libraries.
By the way, I re-compiled Vim with python/python3 in Debian wheezy 64 bit with

```
$ CONFIGURE_OPTS="--enable-shared" pyenv install 2.7.6
$ CONFIGURE_OPTS="--enable-shared" pyenv install 3.4.0
$ pyenv local --unset
$ pyenv shell --unset
$ pyenv global 2.7.6 3.4.0
$ pyenv versions
   system
 * 2.7.6 (set by /home/XXXX/.pyenv/version)
 * 3.4.0 (set by /home/XXXX/.pyenv/version)
   XXXXX
$ python --version
Python 2.7.6
$ python3 --version
Python 3.4.0
$ hg clone https://code.google.com/p/vim/
$ cd vim
$ LDFLAGS="-Wl,-rpath=${HOME}/.pyenv/versions/2.7.6/lib:${HOME}/.pyenv/versions/3.4.0/lib" ./configure \
    --enable-fail-if-missing \
    --enable-luainterp \
    --enable-perlinterp \
    --enable-pythoninterp=dynamic \
    --enable-python3interp=dynamic \
    --enable-tclinterp \
    --enable-rubyinterp=yes \
    --enable-multibyte \
    --enable-fontset \
    --enable-gui=gnome2 \
    --with-features=huge \
    --with-luajit
$ make
```

Then following should work in latest vim (not MacVim, I confirmed that MacVim could not handle python and python3 same time)

```
:python print(sys.version)
:python3 print(sys.version)
```

**However the steps above might not work in your system**. I did that a long time ago and I'm not really sure if it works now. Additionally **it was really hard to figure out the way above thus please do not ask questions about the way to re-compile**. This repository is just a vim plugin's repository and I'm just an author of the plugin thus Google is better than me for such kind of things ;-)
